//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int OrderID { get; set; }
        [Required]
        public Nullable<int> ProductID { get; set; }
        [Required]
        public string CustomerName { get; set; }

        [Required]
        public int UnitsOrdered { get; set; }
        public decimal TotalAmount { get; set; }

        public virtual Product Product { get; set; }

    }
}
